package ge.edu.freeuni.emis.emisapp.loaders.enums;

public enum GradeJSONType {
    SEMESTER, CLASS_LIST, NAME, LECTURERS, CRED, GRADE, INDICATOR, TOTAL_SCORE,
    DETAILED, CATEGORY, CATEGORY_SCORE, LECTURER_NAME,
    DETAILED_NUMBER, DETAILED_SCORE, DETAILED_MAXSCORE, DETAILED_WEIGHT, DETAILED_RESULT
}
